name: Deploy to shop VM

on:
  push:
    branches: [ main ]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
        - name: 코드 체크아웃
          uses: actions/checkout@v4
        
        - name: JDK 설정 (JAVA 21)
          uses: actions/setup-java@v3
          with:
            java-version: '21'
            distribution: 'temurin'
        
        - name: 서버 빌드
          working-directory: shop 
          run: ./gradlew clean build --exclude-task test


        - name: VM에 대상 디렉토리 권한 설정
          uses: appleboy/ssh-action@v1
          with:
            host: ${{ secrets.SSH_HOST_NAME }}
            username: ${{ secrets.VM_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.SSH_PORT || 22 }}
            script: |
              mkdir -p /opt/shop-service/study-spring-be/shop/build/libs/
              sudo chown -R ${{ secrets.VM_USER }}:${{ secrets.VM_USER }} /opt/shop-service/study-spring-be/shop/build/libs/

        - name: 빌드된 JAR 파일 이름 가져오기
          id: get_jar_name
          run: |
            JAR_FILE_PATH=$(find shop/build/libs -name "shop-*.jar" -type f | head -n 1)
            echo "::set-output name=path_with_jar::${JAR_FILE_PATH}"
            JAR_FILE_ONLY=$(basename "${JAR_FILE_PATH}")
            echo "::set-output name=jar_file_only::${JAR_FILE_ONLY}"

        - name: Copy files via SSH
          uses: appleboy/scp-action@v1
          with:
            host: ${{ secrets.SSH_HOST_NAME }}
            username: ${{ secrets.VM_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.SSH_PORT || 22 }}
            source: shop/build/libs/*.jar
            target: /opt/shop-service/study-spring-be/shop/build/libs/